#!/usr/bin/perl
my ($info,$samples,@oid)=@ARGV;
my @info=split/[:]/,$info;
my $ip=$info[0];my $port=$info[1];my $community=$info[2]; $size=@oid;
#print $ip, $port,$community,$samples,$oid[0],$oid[2],$size;
my @st;
my @prev_val=();
my $i=0;
my $j=0;
	while (1){
	@st=`snmpget -v1 $ip:$port -c $community @oid;sleep $samples;`;
	#print("@st\n");
	for($i=0;$i<=$#st;$i++){
        @b=split/[=]/,$st[$i];
        push @val,$b[0];
        #print("@val\n");
        @c=split/[ ]/,$b[1];
        #print("$c[2]\n");
        push @d ,$c[2];
        #print("@d\n"); 
}
        @new_val=@d;
        #print("@f");
        #print("$#f");
        undef @d;
        @val1= @val;
        undef @val;
        #print("$val1[0]\n");
        #print("$#val1\n");
        if(@prev_val){
        for ($i=0;$i<=$#st;$i++){
        $rate=$new_val[$i]-$prev_val[$i];
        $f_rate= $rate/$samples;
        if($f_rate>0){
        STDOUT -> printflush("$val1[$i]= $f_rate\n");
       
}
        else {
     
        $r=4294967296;
        $q=$r/$samples;
        $fn_rate =$f_rate+$q;
        print("$val1[$i]= $fn_rate\n");
             
}

}
}
        @prev_val=@new_val;     

}


